DROP DATABASE IF EXISTS PETS_HEAVEN;
CREATE DATABASE IF NOT EXISTS PETS_HEAVEN;
CREATE TABLE PETS_HEAVEN.propietarios(
    id_pro INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL, 
    correo VARCHAR(100) NOT NULL,
    contrasena VARCHAR(100) NOT NULL, 
    telefono VARCHAR(20) NOT NULL, 
    foto TEXT NOT NULL
)